### ISSUE TITLE
Hide "Twitter Blue" button

### ISSUE THREAD

**Issue by ilyessensei** [oslego/better-twitter#58]
Hi ! Could you make an option to hide this hideous button from my sight thank u <3
Great plug-in btw !!

![image](https://user-images.githubusercontent.com/73798871/216692445-3e72d725-3ee4-4374-9b90-20b8e57fa4e7.png)

**Comment by daira** [comment]
Seconded. Actually I came here to see whether the extension did this, and would install it in a second if it did.

**Comment by sapondanaisriwan** [comment]
```css
a[aria-label="Twitter Blue"] {
     display: none;
}
```
